"""empty message

Revision ID: 49d2525ea31d
Revises: 
Create Date: 2023-05-07 19:29:55.898313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "49d2525ea31d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "first_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "middle_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("date_of_birth", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "location", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column(
            "image_file", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "password", sa.VARCHAR(length=60), autoincrement=False, nullable=False
        ),
        sa.Column(
            "joined_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("active_record", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint("email", name="user_email_key"),
        sa.UniqueConstraint("username", name="user_username_key"),
    )
    # ### end Alembic commands ###
